version: '3.8'

services:

  ui-retaguarda:
    build: ./ui-retaguarda
    ports:
      - "3000:3000"
    depends_on:
      - ms-retaguarda
    # command: tail -F anything     
    env_file:
      - ./ms-retaguarda/.env.dev

  ms-retaguarda:
    build: ./ms-retaguarda
    ports:
      - "3001:3001"
    depends_on:
      - db
    # command: tail -F anything 
    env_file:
      - ./ms-retaguarda/.env.dev
    volumes:
      - ./ms-retaguarda:/app

  ms-europartner-invoice:
    build: ./ms-europartner-invoice
    ports:
      - "3002:3002"
    depends_on:
      - ms-retaguarda
    # command: tail -F anything 
    env_file:
      - ./ms-europartner-invoice/.env.dev

  db:
    image: mongo:latest
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_LOG_LEVEL: warning

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - ui-retaguarda
      - ms-retaguarda
      - ms-europartner-invoice

volumes:
  mongo-data:
